In [16]:
import pandas as pd 
df = pd.read_csv('dataset_Facebook.csv', header = 0, sep = ';') #загрузим csv в pandas dataframe для анализа (заголовки на первой строке, разделитель ;)

df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [17]:
"""Проанализировать массив данных при помощи языка Python 
(допускается и рекомендуется использование дополнительных библиотек): 
вычисление среднего, максимального/минимального значений, медианы, моды числовых значений 
как для всего массива в целом, так и для каждого типа контента (столбец Type) в отдельности. """

df.describe() # подсчет необходимых метрик, реализуемый одной строкой, но, к сожалению, не показывает моды

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [18]:
# еще можно так

df_metrics = pd.DataFrame([list(df.mean(axis=0)) , list(df.median(axis=0)) , list(df.min(axis=0)),  list(df.max(axis=0))], columns=list(df.columns.values), index=['mean', 'median', 'min', 'max' ])
df_metrics

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
mean,123194.176,1.88,7.038,4.15,7.84,0.278557,13903.36,29585.948,920.344,798.772,1415.13,16766.376,6585.488,609.986,7.482,177.945892,27.266129,212.12,NaN
median,129600.000,2,7.000,4.00,9.00,0.000000,5281.00,9051.000,625.500,551.500,851.00,6255.500,3417.000,412.000,3.000,101.000000,19.000000,123.50,NaN
min,81370.000,Link,1.000,1.00,1.00,1.000000,0.00,238.000,570.000,9.000,9.00,9.000,567.000,236.000,9.000,0.000000,0.000000,0.00,0.0
max,139441.000,Video,3.000,12.00,7.00,23.000000,1.00,180480.000,1110282.000,11452.000,11328.00,19779.000,1107833.000,51456.000,4376.000,372.000000,5172.000000,790.00,6334.0

In [26]:
#также можно посчитать все метрики вручную

index = [0] #создаем индексы для нового data frame

all_types_df = pd.DataFrame(  data = { 'metric_type' : 'mean' , 
             'Page total likes': df['Page total likes'].mean(),                        
             'Lifetime Post Total Reach': df['Lifetime Post Total Reach'].mean(), 
             'Lifetime Post Total Impressions': df['Lifetime Post Total Impressions'].mean(), 
             'Lifetime Engaged Users': df['Lifetime Engaged Users'].mean(), 
             'Lifetime Post Consumers' : df['Lifetime Post Consumers'].mean(), 
             'Lifetime Post Consumptions' : df['Lifetime Post Consumptions'].mean(), 
             'Lifetime Post Impressions by people who have liked your Page' : df['Lifetime Post Impressions by people who have liked your Page'].mean(), 
             'Lifetime Post reach by people who like your Page' : df['Lifetime Post reach by people who like your Page'].mean(), 
             'Lifetime People who have liked your Page and engaged with your post' : df['Lifetime People who have liked your Page and engaged with your post'].mean(), 
             'comment': df['comment'].mean() , 
             'like' : df['like'].mean() , 
             'share' :df['share'].mean(), 
             'Total Interactions' : df['Total Interactions'].mean() } , index=index )

median_line = {'metric_type' : 'median' ,
               'Page total likes': df['Page total likes'].median(),  
               'Lifetime Post Total Reach': df['Lifetime Post Total Reach'].median(), 
             'Lifetime Post Total Impressions': df['Lifetime Post Total Impressions'].median(), 
             'Lifetime Engaged Users': df['Lifetime Engaged Users'].median(), 
             'Lifetime Post Consumers' : df['Lifetime Post Consumers'].median(), 
             'Lifetime Post Consumptions' : df['Lifetime Post Consumptions'].median(), 
             'Lifetime Post Impressions by people who have liked your Page' : df['Lifetime Post Impressions by people who have liked your Page'].median(), 
             'Lifetime Post reach by people who like your Page' : df['Lifetime Post reach by people who like your Page'].median(), 
             'Lifetime People who have liked your Page and engaged with your post' : df['Lifetime People who have liked your Page and engaged with your post'].median(), 
             'comment': df['comment'].median() , 
             'like' : df['like'].median() , 
             'share' :df['share'].median(), 
             'Total Interactions' : df['Total Interactions'].median() }  
all_types_df = all_types_df.append(median_line, ignore_index = 'True')

min_line = {'metric_type' : 'min',
            'Page total likes': df['Page total likes'].min(),  
            'Lifetime Post Total Reach': df['Lifetime Post Total Reach'].min(), 
             'Lifetime Post Total Impressions': df['Lifetime Post Total Impressions'].min(), 
             'Lifetime Engaged Users': df['Lifetime Engaged Users'].min(), 
             'Lifetime Post Consumers' : df['Lifetime Post Consumers'].min(), 
             'Lifetime Post Consumptions' : df['Lifetime Post Consumptions'].min(), 
             'Lifetime Post Impressions by people who have liked your Page' : df['Lifetime Post Impressions by people who have liked your Page'].min(), 
             'Lifetime Post reach by people who like your Page' : df['Lifetime Post reach by people who like your Page'].min(), 
             'Lifetime People who have liked your Page and engaged with your post' : df['Lifetime People who have liked your Page and engaged with your post'].min(), 
             'comment': df['comment'].min() , 
             'like' : df['like'].min() , 
             'share' :df['share'].min(), 
             'Total Interactions' : df['Total Interactions'].min() }  
all_types_df = all_types_df.append(min_line, ignore_index = 'True')

max_line = {'metric_type' : 'max',
            'Page total likes': df['Page total likes'].max(),  
            'Lifetime Post Total Reach': df['Lifetime Post Total Reach'].max(), 
             'Lifetime Post Total Impressions': df['Lifetime Post Total Impressions'].max(), 
             'Lifetime Engaged Users': df['Lifetime Engaged Users'].max(), 
             'Lifetime Post Consumers' : df['Lifetime Post Consumers'].max(), 
             'Lifetime Post Consumptions' : df['Lifetime Post Consumptions'].max(), 
             'Lifetime Post Impressions by people who have liked your Page' : df['Lifetime Post Impressions by people who have liked your Page'].max(), 
             'Lifetime Post reach by people who like your Page' : df['Lifetime Post reach by people who like your Page'].max(), 
             'Lifetime People who have liked your Page and engaged with your post' : df['Lifetime People who have liked your Page and engaged with your post'].max(), 
             'comment': df['comment'].max() , 
             'like' : df['like'].max() , 
             'share' :df['share'].max(), 
             'Total Interactions' : df['Total Interactions'].max() }  
all_types_df = all_types_df.append(max_line, ignore_index = 'True')

mode_line = {'metric_type' : 'modes',
             'Page total likes': df['Page total likes'].mode(),  
            'Lifetime Post Total Reach': df['Lifetime Post Total Reach'].mode(), 
             'Lifetime Post Total Impressions': df['Lifetime Post Total Impressions'].mode(), 
             'Lifetime Engaged Users': df['Lifetime Engaged Users'].mode(), 
             'Lifetime Post Consumers' : df['Lifetime Post Consumers'].mode(), 
             'Lifetime Post Consumptions' : df['Lifetime Post Consumptions'].mode(), 
             'Lifetime Post Impressions by people who have liked your Page' : df['Lifetime Post Impressions by people who have liked your Page'].mode(), 
             'Lifetime Post reach by people who like your Page' : df['Lifetime Post reach by people who like your Page'].mode(), 
             'Lifetime People who have liked your Page and engaged with your post' : df['Lifetime People who have liked your Page and engaged with your post'].mode(), 
             'comment': df['comment'].mode() , 
             'like' : df['like'].mode() , 
             'share' :df['share'].mode(), 
             'Total Interactions' : df['Total Interactions'].mode() }  
all_types_df = all_types_df.append(mode_line, ignore_index = 'True')

all_types_df

,metric_type,Page total likes,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,mean,123194,13903.4,29585.9,920.344,798.772,1415.13,16766.4,6585.49,609.986,7.482,177.946,27.2661,212.12
1,median,129600,5281,9051,625.5,551.5,851,6255.5,3417,412,3,101,19,123.5
2,min,81370,238,570,9,9,9,567,236,9,0,0,0,0
3,max,139441,180480,1.11028e+06,11452,11328,19779,1.10783e+06,51456,4376,372,5172,790,6334
4,modes,0 136393 dtype: int64,0 677 1 2232 2 2645 3 293...,0 4372 1 6503 2 7004 3 8533 4 ...,0 537 dtype: int64,0 182 1 298 2 319 3 322 4 335 5...,0 431 1 513 2 599 3 652 4 719 5...,0 1210 1 1284 2 2541 3 2888 4 3...,0 690 1 704 2 1228 3 164...,0 403 dtype: int64,0 0 dtype: int64,0 98.0 dtype: float64,0 13.0 1 14.0 dtype: float64,0 0 1 39 2 75 dtype: int64

In [27]:
# теперь посмотрим все метрики для каждого type в отдельности:

df['Type'].drop_duplicates() #посмотрим, какие бывают type

0      Photo
1     Status
22      Link
29     Video
Name: Type, dtype: object

In [28]:
df.loc[df['Type'] == 'Photo'].describe() #найдем метрики для типа photo

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,426.000000,426.000000,426.000000,426.000000,426.000000,425.000000,426.000000,4.260000e+02,426.000000,426.000000,426.000000,4.260000e+02,426.000000,426.000000,426.000000,425.000000,422.000000,426.000000
mean,122354.171362,1.917840,6.805164,4.107981,7.997653,0.280000,13137.814554,2.899450e+04,818.946009,690.431925,1299.025822,1.642248e+04,6059.103286,507.305164,7.492958,182.611765,27.158768,216.579812
std,16324.528694,0.884007,3.234676,2.056286,4.413082,0.449528,22877.787010,8.095792e+04,868.447092,731.712670,1965.996628,6.450149e+04,7819.018244,399.972665,22.522275,345.245233,44.919679,405.709232
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.000000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.000000,0.000000,0.000000,0.000000
25%,109670.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3092.500000,5.390000e+03,399.000000,335.000000,513.000000,3.695250e+03,2100.250000,300.250000,1.000000,57.000000,10.000000,71.250000
50%,128032.000000,2.000000,7.000000,4.000000,9.000000,0.000000,4675.000000,8.118500e+03,605.500000,528.500000,827.000000,5.498000e+03,3110.000000,403.000000,3.000000,100.000000,19.000000,122.000000
75%,136013.000000,3.000000,10.000000,6.000000,11.000000,1.000000,10571.000000,1.701375e+04,949.000000,832.250000,1327.500000,9.823000e+03,5577.000000,569.750000,7.000000,186.000000,32.000000,225.000000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.000000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,3430.000000,372.000000,5172.000000,790.000000,6334.000000

In [22]:
df.loc[df['Type'] == 'Status'].describe() #найдем метрики для типа Status

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
mean,132647.044444,2.022222,9.066667,4.577778,7.244444,0.222222,13078.888889,24244.466667,2040.222222,1949.555556,2838.866667,18664.266667,9908.577778,1719.844444,8.911111,176.711111,31.422222,217.044444
std,7902.145290,0.398228,2.553073,1.924588,3.926342,0.420437,5218.086371,9929.142874,1351.996838,1319.980433,2075.419548,7521.069017,3997.608572,1083.684581,12.451400,150.772499,24.272589,178.479940
min,104070.000000,1.000000,3.000000,1.000000,2.000000,0.000000,3930.000000,7509.000000,128.000000,86.000000,112.000000,5009.000000,2410.000000,101.000000,0.000000,13.000000,1.000000,17.000000
25%,131300.000000,2.000000,7.000000,3.000000,3.000000,0.000000,9232.000000,17099.000000,1151.000000,1073.000000,1512.000000,13887.000000,7360.000000,995.000000,2.000000,86.000000,16.000000,106.000000
50%,135713.000000,2.000000,10.000000,5.000000,9.000000,0.000000,11096.000000,20849.000000,1701.000000,1599.000000,2201.000000,17502.000000,8980.000000,1604.000000,4.000000,150.000000,28.000000,186.000000
75%,138353.000000,2.000000,12.000000,6.000000,10.000000,0.000000,15816.000000,30514.000000,2675.000000,2567.000000,3420.000000,22103.000000,11792.000000,2256.000000,10.000000,226.000000,39.000000,265.000000
max,139441.000000,3.000000,12.000000,7.000000,15.000000,1.000000,31136.000000,59964.000000,6164.000000,5934.000000,9237.000000,37849.000000,21352.000000,4376.000000,60.000000,859.000000,123.000000,1009.000000

In [23]:
df.loc[df['Type'] == 'Link'].describe() #найдем метрики для типа Link

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,116363.181818,1.136364,6.590909,4.272727,5.727273,0.272727,18544.590909,28725.454545,342.818182,292.681818,374.090909,11148.590909,6544.363636,210.545455,2.818182,73.318182,12.909091,89.045455
std,21459.767350,0.467563,4.563406,1.856310,3.930126,0.455842,21399.411331,50042.047711,340.174414,291.385261,358.404787,8888.568907,5960.612461,188.873030,3.633657,85.746240,11.751025,95.720564
min,85979.000000,1.000000,1.000000,1.000000,2.000000,0.000000,1536.000000,3094.000000,24.000000,23.000000,26.000000,2307.000000,1180.000000,19.000000,0.000000,5.000000,0.000000,6.000000
25%,98829.250000,1.000000,3.000000,3.000000,3.000000,0.000000,3878.000000,6861.500000,105.000000,84.750000,120.000000,6367.750000,3156.000000,92.250000,0.000000,19.500000,5.500000,32.750000
50%,115396.000000,1.000000,4.500000,4.500000,4.000000,0.000000,7422.000000,9773.000000,244.000000,205.000000,290.000000,9034.500000,5039.000000,161.500000,1.500000,37.000000,10.500000,52.500000
75%,138059.000000,1.000000,11.750000,6.000000,9.250000,0.750000,30938.000000,26153.750000,422.000000,355.750000,472.750000,13903.750000,8140.000000,251.750000,4.000000,110.750000,15.000000,125.000000
max,138895.000000,3.000000,12.000000,7.000000,14.000000,1.000000,70912.000000,229733.000000,1374.000000,1106.000000,1345.000000,42338.000000,27232.000000,788.000000,15.000000,379.000000,44.000000,420.000000

In [24]:
df.loc[df['Type'] == 'Video'].describe() #найдем метрики для типа Video

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,7.000000,7.0,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.00000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,135014.857143,1.0,9.571429,3.571429,8.714286,0.571429,51205.714286,102622.428571,1707.00000,1584.714286,2600.142857,43149.857143,17386.285714,979.428571,12.285714,231.428571,52.142857,295.857143
std,4730.551709,0.0,2.299068,1.511858,4.347961,0.534522,48825.191031,101838.314111,1174.78608,1160.701471,2296.643524,31072.683306,9861.583607,650.805362,8.693183,142.025652,42.643595,183.992236
min,126424.000000,1.0,6.000000,2.000000,2.000000,0.000000,13544.000000,30235.000000,459.00000,411.000000,539.000000,21436.000000,9568.000000,363.000000,2.000000,65.000000,13.000000,81.000000
25%,132835.000000,1.0,8.000000,2.500000,6.500000,0.000000,19144.000000,36181.500000,829.00000,763.000000,1197.500000,25644.500000,12340.000000,503.000000,4.000000,121.000000,13.500000,144.000000
50%,137893.000000,1.0,11.000000,3.000000,11.000000,1.000000,30624.000000,56950.000000,1779.00000,1643.000000,2331.000000,30131.000000,14112.000000,885.000000,17.000000,204.000000,44.000000,271.000000
75%,138111.000000,1.0,11.000000,4.500000,11.000000,1.000000,68488.000000,140854.500000,2090.50000,1845.500000,2804.500000,45845.500000,17312.000000,1192.000000,18.000000,330.000000,80.000000,440.500000
max,138895.000000,1.0,12.000000,6.000000,13.000000,1.000000,139008.000000,277100.000000,3872.00000,3822.000000,7327.000000,107502.000000,38720.000000,2218.000000,23.000000,449.000000,121.000000,550.000000

In [31]:
"""Найти самый популярный объект в выборке, объяснить почему.

Для начала разберемся в смысле предложенных метрик:

•	Lifetime Post Total Reach – количество уникальных пользователей, просмотревших пост;
•	Lifetime Post Total Impressions – количество показов (возможно несколько показов для одного человека);
•	Lifetime Engaged Users  and Lifetime Post Consumers - количество уникальных пользователей, которые кликнули пост. 
Engagement включает все клики приводящие к story. 
Consumption включает в себя все клики, независимо от того, приводят ли они к story или нет. 
В целом, метрики очень похожи, но для анализа популярности поста важнее количество любых кликов, 
тк они учитывают любые взаимодействия пользователя с контентом, 
включае те, которые не оставляют следов в story; 
Link https://brnrd.me/posts/engagement-vs-consumption-the-facebook-dilemma 
•	Lifetime Post Consumptions – количество всех кликов;
•	Lifetime Post Impressions by people who have liked your Page – количество показов пользователям, которые лайнкули страницу 
•	Lifetime Post reach by people who like your Page - количество показов уникальным пользователям, которые лайкнули страницу
•	Lifetime People who have liked your Page and engaged with your post - количество пользователей, которые лайкнули страницу и взаимодейстовали с постом. 

По моему мнению, популярность можно измерить количеством уникальных пользователей, 
которые просмотрели пост и, в то же время, пост их настолько заинетересовал,
что они начали взаимодействие с ним - начали его кликать.
Поэтому, как меру популярности необходимо выбрать Lifetime Post Consumers.
Выберем топ пост с самой высокой метрикой LPC:"""

df.sort_values(by = 'Lifetime Post Consumers', ascending=False).head(1)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
446,96749,Photo,1,3,1,2,1.0,98816,125026,11452,11328,18115,16682,10336,1356,10,197.0,21.0,228